### PR TITLE
Add sourcecred/sourcecred-action repository

### PR DESCRIPTION
**Pull request by Beanow**
Holding @vsoch's work on example actions. Should track that :]

### CODE REVIEW

**Comment by vsoch** [comment]
The last two to test for the automated / pull request generated prototypes should trigger tomorrow in the AM, I can update here when things look good :)

**Comment by Beanow** [comment]
> The last two to test for the automated / pull request generated prototypes should trigger tomorrow in the AM, I can update here when things look good :)

No need to follow up for this PR I think :slightly_smiling_face:.
Instead a good way to track this could be using an [Initiative](https://discourse.sourcecred.io/t/about-the-initiatives-category/242).

This change is to include the repository's interactions (issues, PRs, commits, comments, etc.) in our canonical cred scores (e.g. the scores we use for [the CredSperiment](https://discourse.sourcecred.io/t/about-the-credsperiment/181) and [Payouts](https://discourse.sourcecred.io/t/sourcecred-contributor-payouts/298)). That should work without any particular deliverable.

**Comment by Beanow** [comment]
Note: #9 was accidentally merged into this as they were set up as dependencies.
I'll make a replacement PR for #9 and remove the commit from this PR.

**Comment by vsoch** [comment]
Happy 2020 @Beanow ! I think you probably beat me to it :)

**Comment by Beanow** [comment]
Happy new year :D :fireworks:

**Comment by Beanow** [comment]
@decentralion same issue here, can't merge because it requires commit signing.

**Pull request merged**
