### PR TITLE
Propose a transfer from @s_ben to @protocol

### PR DESCRIPTION
**Pull request by decentralion**
Thanks to @pk-controller for discussions around our new transfer format.

### CODE REVIEW

**Comment by decentralion** [comment]
First run of the new Protocol. Requests are:

@s-ben: Please comment on the PR confirming that you want this transfer.

@pk-controller: Once @s-ben has confirmed, please initiate the wire for $2492.02 and approve this PR.

I'll then merge it.

**Comment by s-ben** [comment]
ACK (conform payment)

**Comment by pk-controller** [comment]
Payment initiated

**Comment by s-ben** [comment]
Received 👍

**Pull request merged**
