### PR TITLE
Community call initiatives

### PR DESCRIPTION
**Pull request by Beanow**
Relates to Cred issue: #38 
Trying out a way of representing them.
cc @s-ben 

Haven't added everything yet. Wanted to give a chance to look at the approach here.

I'm going off memory what the ballpark weights were we previously talked about.
Currently using: 100 for completion, 50 for notes, 50 for recordings.

One thing that stands out is, it seems a new feature is emerging. Minting cred on things that already have a URL. Though some of these (discourse) exist in the graph and could be used for attribution by minting on a reference-detected node. Others do not (roam in other PRs, google drive here) exist in the graph and may need a node added by the initiatives plugin to represent it.

There's also a lot if interesting things coming out of comparing the before/after scores with this. Which I'll write up another comment for.

### CODE REVIEW

**Comment by decentralion** [comment]
What if instead of making it a fixed "100 for call", what if we used 20 * numContributors instead? I like the idea that the cred in the call scales with participants, and I'd like participating in the calls to earn a meaningful flow of cred.

We could implement this by having the 20*nContributors weight apply directly on the "particpants" node, we could also make one participation node per contributor, each with a weight of 20.

**Comment by Beanow** [comment]
That makes sense and I'm down to try that out. :+1:

Though I do think it's still a proxy for value, maybe even a baseline to reduce risk, not a direct measure of value. I think it's important we make sure the edges make enough sense that we can increase the Cred of the Initiative itself (such as when boosting) and/or flow Cred through it (such as being a reference/contribution/dependency for something else).

I'm imagining what people could do to optimize for the incentives. And having max attendance and as many participants as possible imo isn't the end goal. Calls could also be valuable because they were super fascinating, encouraging, or we had remarkably good communicators on the call, or found ways to unblock some major milestone, etc. So having the Initiatives ready to receive additional Cred for other measures of value changes the optimization strategy to not just attend and bring many bodies, but also make it an overall success so other sources of Cred may be added :]

**Comment by Beanow** [comment]
Updated to have the 20x participants setup. A quick probe of the results suggests this is an improvement to my subjective sense. Going with this on the premise that some cred for these initiatives is better than no cred. With better analysis tools we should be able to balance this better.

**Comment by Beanow** [comment]
Considering 20x for a participant, I think the organizing weights are probably high by comparison.
If a participant receives 20 Cred on average, taking notes and recording would result in 120 Cred if those are 50 each. Plus receiving Cred flow from the Champion edge on top of that.

Doing some tests, this put @s-ben an order of magnitude above all other contributors.
With the top contributors looking like:
| Contributor | Before | After | Change |
|---|---:|---:|---:|
|identity/s_ben                 |  4218|  5558| 1339.5|
|identity/decentralion          | 32601| 33004|  402.5|
|identity/Beanow                | 11785| 12044|  259.3|

So I changed this to not use champions, and make notes/recording 20 Cred each.
| Contributor | Before | After | Change |
|---|---:|---:|---:|
|identity/s_ben                 |  4218|  4820|  601.9|
|identity/decentralion          | 32601| 32993|  391.6|
|identity/Beanow                | 11785| 12054|    269|

I feel like these numbers still need more balancing. Current Initiative edge weights seem very sensitive to existing Cred of contributors. It's part of why I'm not including everyone, as reading into these numbers atm doesn't seem helpful to me.

What I was going for here, is to make sure @s-ben's additional cred for organizing is in a plausible range. @decentralion has 100% attendance, and high existing cred, so the best-case scenario as a participant here.

In terms of absolute Cred, this feels on the low end to me as well. So I think these are also candidate for doubling as we're happy with the settings and Initiatives.

**Pull request closed without merging**
