### PR TITLE
Log grain buys

### PR DESCRIPTION
**Pull request by s-ben**
This PR logs recent grain buys from Protocol Labs (PL) not yet reflected in the ledger. Specifically, it translates USDC sent from PL to SourceCred into Grain buys (transfers from `sourcecred` to `protocol`). 

Below are the three USDC transfers that are converted into Grain, which add up to 500,000 USDC. 

125k USDC from PL 7/2/2021
https://etherscan.io/tx/0x2f50181799c345c8e52dee4143a1a1fae74633ffec78cb701da0c2db3755a60b

125k from PL on 5/17/2021
https://etherscan.io/tx/0xf16be2a916ebd1c8041958401f24cf9acdeac9bbbf1bfcfcb43cf8e5b73ee813

250k from PL on 3/8/2021
https://etherscan.io/tx/0x14e9ead1713c8f1870a30f11b915f396271fa33939e556b9f38417bd57684fc7

Note: this is based on the fact that the last Grain transfer to PL was on 1/13/2021.
image

It is assumed that this 'catches up' PL, and takes into account its previous transfers. The 500,000 transferred in this PR is simply the sum of all transfers since 1/31.

### CODE REVIEW

**Comment by blueridger** [comment]
Looks good. Needs rebased, and there's a typo in the memo

**Comment by blueridger** [comment]
You made the assumption that everything before January 2021 is up-to-date and logged. Is this a safe assumption? Shouldn't PL have 1 million grain from 2020 alone?

**Comment by s-ben** [comment]
Yes, I assumed that if @panchomiguel transferred Grain to PL on Jan 13th, and didn't update it after, this probably included all owed transfers. However, I realize that's a big assumption. That is why I tagged @panchomiguel and @decentralion for review and in review request on Discord. Have not heard anything from either. Ping ^^

**Comment by blueridger** [comment]
Since PL hasn't had any outbound Grain transactions, I'm wondering if we could just look at the all time total we've received from PL on chain and just give them Grain to put their balance at that number.

**Comment by s-ben** [comment]
That seems sensible to me. Though does make the assumption that all PL transfers have gone to buy Grain at 1-to-1 peg. That makes sense to me, but wondering if there are any complicating factors we're not aware of? Since we're doing core meeting this week, have added discussing this to the Core meeting agenda: https://roamresearch.com/#/app/SourceCred/page/CEcdOZA7Q

Feel free to remove if you think there's a better avenue.

**Review by decentralion — APPROVED** [review]
Heya -- just seeing this, sorry, haven't been watching GitHub notifications, my SC pings are  noisy with group mentions, etc, so I sometimes miss direct mentions. In the future, please feel free to DM me directly if there's something blocking on me.

I agree that you can't simply assume that all Grain purchases before this year were correctly logged. However, it's not as simple as saying that PL's grain should equal the total amount that they've sent to `sourcecred.eth` either -- PL has also earned Grain through some direct Cred, via the sponsorships, etc. The only correct way to find their balance will be to identify all of the transactions that weren't properly accounted during @panchomiguel's era as treasurer.

Here is a table recording all of the Grain transfers to PL in the history of the ledger: 

| Date | From | To | Amount | Memo | 
| ---  | --- | --- | --- | --- |
| 7/29/2020 | s-ben | protocol | 112g | https://discourse.sourcecred.io/t/credsperiment-week-3-distribution/282/8 |
| 7/29/2020 | s-ben | protocol | 900g | https://github.com/sourcecred/cred/pull/5 |
| 7/29/2020 | s-ben | protocol | 2,492g | https://github.com/sourcecred/cred/pull/6 |
| 7/29/2020 | s-ben | protocol | 9,000g | https://etherscan.io/tx/0x439fd45f47f4b263d0294e0dab4b3cc53202631adc5e646321694ab4ee4b476b |
| 8/21/2020 | s-ben | protocol | 14,344g | https://etherscan.io/tx/0xb85ae76fe8c8a169a6b0eae25ceee2c56f172baab63e964f09c811c04ccedb5c |
| 8/21/2020 | lbstrobbe | protocol | 28,000g | Payment via banking system |
| 8/26/2020 | KuraFire | protocol | 3,648g | https://etherscan.io/tx/0x2f3e511e4dacde40c3d7b59f38ba8dcc737dd7f66d022ea178cce97a2a52f586 and https://etherscan.io/tx/0xa6f0ebc2834bc025ca0c78a8bd7db81662ffbc970f263ba6ae2d09cafc9ea928 |
| 8/26/2020 | sourcecred | protocol | 8,072g | https://etherscan.io/tx/0x9a6a5ad67d891ca0b997e40433cae56d0a858ca0a68b4b02a49c16e7c5250fa1 |
| 9/9/2020 | hammad | protocol | 8,000g | https://etherscan.io/tx/0xe33611c27c698b32ee0f8327c65c50fae121a06c9ed99d905fb2263728302cba |
| 9/23/2020 | sourcecred | protocol | 6,800g | https://etherscan.io/tx/0x10683417b0ddc28b543e578074d23b571e139c5fc4c4ea44596ec37d16e35da0 |
| 11/20/2020 | sourcecred | protocol | 17,177g | https://etherscan.io/tx/0xb8f4854d0b6e83fbcd66f2133c4720ef79d90c442ea386a0a5dadd4d0ac36733 , This is being recorded late |
| 11/20/2020 | sourcecred | protocol | 27,865g | https://etherscan.io/tx/0x1686f9dd341ef60ccd6645c03fae65e123d0cdb6924907327453d1381157ef67 , recorded late |
| 1/4/2021 | sourcecred | protocol | 76,428g | https://etherscan.io/tx/0x0edacb746db61bc85ad46c766ad19e827d933c3d343033186c199b67200c81c9 |
| 1/31/2021 | sourcecred | protocol | 200,000g | https://etherscan.io/tx/0x4b23abf09bf9ee5d394834c2c765008de7344b25caddcd0f205144a453b83dea and https://etherscan.io/tx/0x2f7dbf8565282d2c93719ab61255bce86f1f2a8cc56c995bfe84569419c9cee2 |

(As generated via [this notebook](https://observablehq.com/d/d16a595ec12f2fde).)

Looking at this data, it does actually seem like we have accurate records up through the beginning of 2021, since we did a reconciliation in November 2020 and then it seems like we were propelry recording transfers thru 1/31. So I think we only have 500k Grain that needs to be added, and it's accurately reflected here. 

For ease of future auditing, I suggest you update this PR so that the memo includes links to the 3 USDC transactions that this PR is updating balances for. It's a very helpful habit to document things for precisely when issues like this come up.

Anyway, approved.

**Review by blueridger — COMMENTED** [review]
rebase and redo please

**Comment by s-ben** [comment]
Fell into a git hole trying to rebase, so just redid changes off fresh main in new PR,
https://github.com/sourcecred/cred/pull/347

Added the three etherscan txs in the memo this time for future auditing.

**Comment by blueridger** [comment]
https://github.com/sourcecred/cred/pull/347

**Pull request closed without merging**
