### PR TITLE
Add identity for vsoch

### PR DESCRIPTION
**Pull request by Beanow**
Continues from #8

Maps @vsoch to her new Discourse account.

### CODE REVIEW

**Comment by vsoch** [comment]
oh cool! I knew discourse had a plugin, but didn't connect those two things to deduce that it was setup for actual sourcecred... sourcecred! Super awesome :)

**Comment by Beanow** [comment]
> oh cool! I knew discourse had a plugin, but didn't connect those two things to deduce that it was setup for actual sourcecred... sourcecred! Super awesome :)

Yes :] quite a lot of our cred comes from the forums. This uses a 3rd plugin ([identity](https://github.com/sourcecred/sourcecred/tree/master/src/plugins/identity)) to combine your accounts.

This matters quite a bit for cred, because now the "weight" from both github and discourse is merged as well. In your case, most of your cred is currently in github. After this is merged your likes :heart: on discourse will have a stronger effect, because they'll carry the weight of your github cred as well. While previously they'd be separate.

**Comment by vsoch** [comment]
Gotcha!

**Comment by decentralion** [comment]
Sorry I've been slow in approving this--it adds a bit of complexity because the notebooks for grain issuance are kind of hacky, and there are some bugs around collapsing identities together when the identities in question have already received Grain. However, I'll merge this and just add a TODO that in next week's grain distribution I need to add a bit more to my special case logic to accommodate these combined identities. :)

**Comment by Beanow** [comment]
Please mind the target for this wasn't master :sweat_smile: but #8

**Pull request merged**
